export async function onRequestPost(context) {
  const { request, env } = context;

  const corsHeaders = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    "Content-Type": "application/json",
  };

  if (request.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  let opp;
  try {
    const body = await request.json();
    opp = body.opp;
  } catch {
    return new Response(JSON.stringify({ error: "Invalid request body" }), {
      status: 400,
      headers: corsHeaders,
    });
  }

  if (!env.ANTHROPIC_API_KEY) {
    return new Response(
      JSON.stringify({ error: "ANTHROPIC_API_KEY not configured" }),
      { status: 500, headers: corsHeaders }
    );
  }

  const prompt = `You are AURUM Investment Intelligence Core — an elite AI combining quantitative, fundamental, technical, and macro analysis used by institutional investors.

Provide a concise, institutional-grade analysis for ${opp.sym} (${opp.name}):
- Current price: $${opp.price}
- Recommended action: ${opp.action.toUpperCase()}
- Entry zone: ${opp.entry}
- Target: $${opp.target}
- Stop loss: ${opp.stop}
- Position size: ${opp.size} of portfolio
- AI Conviction Score: ${opp.conviction}/100

Respond ONLY with valid JSON (no markdown, no backticks, no preamble):
{
  "thesis": "One powerful 2-sentence investment thesis written with conviction",
  "fundamental": "Concise fundamental analysis",
  "technical": "Concise technical analysis",
  "macro": "Key macro tailwind or headwind",
  "keyRisk": "The single most important risk",
  "invalidation": "Specific price or event that would invalidate the thesis",
  "timeHorizon": "Expected trade duration",
  "asymmetry": "Risk/reward ratio"
}`;

  let anthropicResponse;
  try {
    anthropicResponse = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": env.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-sonnet-4-20250514",
        max_tokens: 800,
        messages: [{ role: "user", content: prompt }],
      }),
    });
  } catch (e) {
    return new Response(
      JSON.stringify({ error: "Failed to reach Anthropic API" }),
      { status: 502, headers: corsHeaders }
    );
  }

  if (!anthropicResponse.ok) {
    const errText = await anthropicResponse.text();
    return new Response(
      JSON.stringify({ error: "Anthropic API error", detail: errText }),
      { status: anthropicResponse.status, headers: corsHeaders }
    );
  }

  const data = await anthropicResponse.json();
  const text = data.content?.map((b) => b.text || "").join("") || "";

  let parsed;
  try {
    parsed = JSON.parse(text.replace(/```json|```/g, "").trim());
  } catch {
    parsed = {
      thesis: "Analysis generated by AURUM IIC.",
      fundamental: "Strong fundamental profile with improving metrics.",
      technical: "Constructive technical setup with trend alignment.",
      macro: "Macro conditions broadly supportive.",
      keyRisk: "Monitor for macro regime change.",
      invalidation: "Close below stop loss level invalidates thesis.",
      timeHorizon: "2–4 weeks",
      asymmetry: "3:1",
    };
  }

  return new Response(JSON.stringify(parsed), { headers: corsHeaders });
}

export async function onRequestOptions() {
  return new Response(null, {
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
    },
  });
}
